config/routes.rb
Rails.application.routes.draw do
  root 'innoawards#index'
  # resources :products, except: [:create, :new] do
  #   get 'success', action: :success, on: :collection
  # end

  resources :products, except: [:create, :new] do
    get 'success', action: :success, on: :collection
  end

  # 投票
  # resources :ranks, only: :index
  resources :ranks, only: :index do
    post :vote
  end

  # 主站 oauth 登陆
  get 'users/auth/geekpark' => 'sessions#omniauth', as: :login
  match 'users/auth/:provider/callback' => 'sessions#omniauth', via: [:get, :post]
  delete 'sessions/sign_out', as: :logout

  namespace :admin do
    root 'innoawards#index'

    resources :product_as do
      patch 'add_screenshot', on: :member
      get 'search', on: :collection
    end

    resources :ranks, only: [:new, :create, :update, :destroy]

    # 后台管理 创新产品评选
    resources :innoawards do
      get 'page/:page', action: :index, on: :collection
      resources :awards do
        patch 'change_order', on: :member
      end
      get 'ranks', on: :member
      get 'partners', on: :member
      post 'partners', on: :member, to: 'innoawards#update_partners'

      resources :images, only: [:create, :update, :destroy]
      resources :products do
        get 'page/:page', action: :index, on: :collection
        get 'search', action: :search, on: :collection
        patch 'approve', on: :member
      end
    end

    resources :news

    resources :images, only: [:destroy] do
      post 'create_image', on: :collection
    end

    get 'partners/refresh' => 'partners#refresh'
  end

  get '/innoawards', to: 'innoawards#index'

  get 'upbrowser', to: 'innoawards#upbrowser'

  # mount api
  mount V1::API => '/api'
  mount GrapeSwaggerRails::Engine => 'api_doc'

end

app/models/product.rb
class Product < ActiveRecord::Base
  extend Enumerize

  before_validation :downcase_all
  before_save :check_url
  # after_create :sync_to_product_a

  paginates_per 10

  mount_uploader :logo, LogoUploader
  mount_uploaders :screenshots, ScreenshotUploader

  validates :name, :summary, :description, :url, :published_at, :screenshots,
            :category, :c_name, :c_corp, :c_position,
            :c_email, :c_mobile, :c_corp_addr, presence: true
  #第二年的产品会有重名
  #validates :name, uniqueness: true
  # validates :url, format: { with: /\A(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?\z/ }
  validates :summary, length: 1..80
  validates :description, length: 1..600
  validates_inclusion_of :published_at, in: Date.new(1960, 1, 1)..Date.today
  validates :c_email, format: { with: /\A([a-z0-9_\.-]+)@([\da-z\.-]+)\.([a-z\.]{2,6})\z/ }

  enumerize :status, in: [:waiting, :unapproved, :approved], default: :waiting, scope: true
  enumerize :category, in: [:app, :internet_hardware, :technology, :wechat, :media, :daily_necessaties, :open_platform, :other], default: :app, scope: true

  has_many :awards, through: :ranks
  has_many :ranks, dependent: :destroy
  has_many :innoawards, through: :innoawards_products
  has_many :innoawards_products, dependent: :destroy

  def sync_to_product_a
    return if ProductA.find_by_name(self.name)
    pa = ProductA.new(name: name, summary: summary, description: description, url: url, published_at: published_at, category: category, contacts: [{name: c_name, position: c_position, email: c_email, mobile: c_mobile}])
    pa.logo = File.new(logo.file.path)
    pa.save
    screenshots.each do |ss|
      pa.screenshots.create(file: ss.file)
    end
    pa
  end

  def check_url
    return unless weibo_changed? || url_changed?
    weibo.prepend('http://') unless weibo.start_with?('http')
    url.prepend('http://') unless url.start_with?('http')
  end

  class << self
    def search query
      where("lower(name) like ?", "%#{query.downcase}%")
    end

    def ordered
      order(created_at: :desc)
    end
  end

  def downcase_all
    self.url.downcase!
    self.c_email.downcase!
  end

  def as_my_json inno_id
    {
      name: name,
      logo: logo.url || '/assets/default_logo.jpg',
      summary: summary,
      id: id,
      created_at: created_at.strftime('%Y/%m/%d'),
      category: I18n.t("activerecord.attributes.product.category.#{category || 'empty'}"),
      status: I18n.t("activerecord.attributes.product.status.#{status}"),
      edit_path: Rails.application.routes.url_helpers.edit_admin_innoaward_product_path(innoaward_id: inno_id, id: id),
      path: Rails.application.routes.url_helpers.admin_innoaward_product_path(innoaward_id: inno_id, id: id)
    }
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
  before_action :find_innoaward
  skip_before_action :store_previous_url, only: [:search, :approve, :create, :update, :destroy]

  def index
    @products = @innoaward.products
    @products = @products.with_status(params[:status]) if params[:status]
    @products = @products.order(created_at: :desc).page params[:page]
    gon.products = @products.map{|pro| pro.as_my_json(@innoaward.id)}
    gon.innoaward_id = @innoaward.id
  end

  def search
    @products = Product.search(params[:query])
    products = @products.map{|pro| pro.as_my_json(@innoaward.id)}
    res = {products: products}
    render json: res
  end

  def approve
    @product = Product.find(params[:id])
    @product.update(status: params[:status])
    render json: @product.as_my_json(@innoaward.id)
  end

  def new
    @product = Product.new
  end

  def create
    innoaward = Innoaward.find_by_id(params[:innoaward_id])
    @product = Product.new(product_params)
    if @product.save
      InnoawardsProduct.create(innoaward_id: innoaward.id, product_id: @product.id)
      redirect_to admin_innoaward_products_path(@innoaward)
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_innoaward_products_path(@innoaward)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_innoaward_products_path(@innoaward)
  end

  private

  def product_params
    recommended_platform = params[:product][:recommended_platform]
    params[:product][:recommended_platform] = recommended_platform.split(',').map(&:strip) if (params[:product] && (recommended_platform.is_a? String))
    params
      .require(:product)
      .permit(:name, :logo, :logo_cache, :summary, :description, :url, {screenshots: []},
              :published_at, :weibo, :wechat, :category, {recommended_platform: []},
              :c_name, :c_corp, :c_position, :c_corp_addr, :c_email, :c_mobile, :evaluation)
  end

  def find_innoaward
    @innoaward = Innoaward.find(params[:innoaward_id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  layout :enable_layout

  def index
    @products = Product.order(created_at: :desc).all
  end

  def new
    @product = Product.new
    render "products/2016/new.html.slim"
  end

  def success
    render "products/2016/success.html.slim"
  end

  def create
    innoaward = Innoaward.find_by_year(Date.today.year)
    @product = Product.new(product_params)
    if @product.save
      # InnoawardMailer.new_product_success(@product).deliver_now
      InnoawardsProduct.create(innoaward_id: innoaward.id, product_id: @product.id)
      render json: @product, status: :created, location: @product
    else
      render json: @product.errors.full_messages, status: :unprocessable_entity
    end
  end

  def show
    current_year = available_years.include?(params[:year]) ? params[:year] : available_years.last
    @product = Product.find(params[:id])
    @award = Award.find(params[:award_id])
    @rank = Rank.where(product_id: @product.id, award_id: @award.id).first
    @other_products = @award.products.where.not(id: @product.id).order('ranks.vote')
    # @product.sync_to_product_a
    render "products/#{current_year}/show.html.slim"
  end

  # def edit
  #   @product = Product.find(params[:id])
  # end
  #
  # def update
  #   @product = Product.find(params[:id])
  #   @product.update(product_params)
  #   redirect_to product_path(@product)
  # end
  #
  # def destroy
  #   @product = Product.find(params[:id])
  #   @product.destroy
  #   redirect_to products_path
  # end

  private

  def product_params
    recommended_platform = params[:product][:recommended_platform]
    params[:product][:recommended_platform] = recommended_platform.split(',').map(&:strip) if (params[:product] && (recommended_platform.is_a? String))
    params
      .require(:product)
      .permit(:name, :logo, :logo_cache, :summary, :description, :note, :url, {screenshots: []},
              :published_at, :weibo, :wechat, :category, {recommended_platform: []},
              :c_name, :c_corp, :c_position, :c_corp_addr, :c_email, :c_mobile, :evaluation)
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_error_messages.html.slim
- if errors.try(:any?)
  .ui.warning.message
    .header
      | 请检查您的输入
    ul.list
      - errors.full_messages.each do |e|
        li = e

app/views/admin/products/_form.html.slim
= form_for [:admin, innoaward, product], html: { class: 'ui form' } do |f|
  .two.fields
    .required.field
      = f.label :name, '产品名称'
      = f.text_field :name
    .required.field
      = f.label :url, '产品网址'
      = f.text_field :url
  .required.field
    = f.label :logo, '产品LOGO'
    = image_tag((product.logo.url if product.logo?), id: 'logo-preview')
  .field
    = f.file_field :logo, id: 'logo-input'
    = f.hidden_field :logo_cache
  .required.field#screenshots-preview
    = f.label :screenshots, '产品截图'
    - product.screenshots.each do |ss|
      = image_tag ss.url, size: '200'
  .field
    = f.file_field(:screenshots, multiple: true, id: 'screenshots-input')
  .required.field
    = f.label :summary, '产品简介'
    = f.text_field :summary
  .required.field
    = f.label :description, '产品描述'
    = f.text_area :description
  .required.field
    = f.label :note, '备注'
    = f.text_field :note
  .two.fields
    .required.field
      = f.label :published_at, '上线时间'
      = f.date_field :published_at
    .field
      = f.label :weibo, '微博地址'
      = f.text_field :weibo
  .two.fields
    .required.field
      = f.label :category, '产品类别'
      = f.select :category, options_for_select(Product.category.values.map{|c| [t('activerecord.attributes.product.category.' + c), c]}, product.category || 'app')
    .field
      = f.label :recommended_platform, '推荐平台'
      = f.text_field :recommended_platform, value: product.recommended_platform.try(:join, ', ')
  .three.fields
    .required.field
      = f.label :c_name, '联系人姓名'
      = f.text_field :c_name
    .required.field
      = f.label :c_corp, '联系人公司'
      = f.text_field :c_corp
    .required.field
      = f.label :c_position, '联系人职位'
      = f.text_field :c_position
  .three.fields
    .required.field
      = f.label :c_corp_addr, '联系人公司地址'
      = f.text_field :c_corp_addr
    .required.field
      = f.label :c_email, '联系人邮箱'
      = f.text_field :c_email
    .required.field
      = f.label :c_mobile, '联系人电话'
      = f.text_field :c_mobile
  .field
    = f.label :evaluation, '编辑点评'
    = f.text_field :evaluation
  .field
    = submit_tag '提交', class: 'ui blue button'

app/views/admin/products/edit.html.slim
.container
  = render partial: 'error_messages', locals: { errors: @product.errors }
  = render partial: 'form', locals: {innoaward: @innoaward, product: @product }

app/views/admin/products/index.html.slim
.container
  .ui.grid
    .row
      .four.wide.column
        = render partial: 'admin/innoawards/sidebar', locals: { inno: @innoaward }
      .twelve.wide.column
        .ui.borderless.menu
          .item.header
            | 报名产品
          a.item.ui.button href=new_admin_innoaward_product_path(@innoaward)
            | 添加
          .ui.search.right.item#search-input data-url=search_admin_innoaward_products_path(@innoaward)
            .ui.transparent.icon.input
              input type='text' placeholder='产品名称' v-model='query' v-on="keyup:submit | debounce 300"
              i.search.icon
        .ui.borderless.menu
          a.item href=admin_innoaward_products_path
            | 全部
            .ui.left.pointing.label
              =@products.count
          a.item href="#{admin_innoaward_products_path}?status=waiting"
            | 待审核
            .ui.teal.left.pointing.label
              =@products.with_status(:waiting).count
          a.item href="#{admin_innoaward_products_path}?status=approved"
            | 已通过
            .ui.green.left.pointing.label
              =@products.with_status(:approved).count
          a.item href="#{admin_innoaward_products_path}?status=unapproved"
            | 已拒绝
            .ui.red.left.pointing.label
              =@products.with_status(:unapproved).count

        table.ui.celled.table
          thead
            tr
              th.one.wide Logo
              th.three.wide 名称
              th.two.wide 类型
              /th.two.wide 简介
              th.two.wide 提交时间
              th.two.wide 状态
              th.five.wide 操作
          tbody#result
            tr v-repeat='p in products'
              td
                img src="{{p.logo}}" class='logo'
              td
                a href='{{p.edit_path}}' {{p.name}}
              td 
                ="{{p.category}}"
              td 
                ="{{p.created_at}}"
              td 
                ="{{p.status}}"
              td
                a href='javascript:;' v-on='click: approve(p.id, "approved", $index)'
                  | 通过
                | /
                a href='javascript:;' v-on='click: approve(p.id, "unapproved", $index)'
                  | 拒绝
                | /
                a.choosen href='javascript:;' data-pro-id='{{p.id}}'
                  | 参选
                | /
                a href='{{p.edit_path}}'
                  | 编辑
                | /
                a href='{{p.path}}' data-method='delete' data-confirm='确认删除?'
                  | 删除

        = paginate @products

  .ui.modal#choosen-modal
    i.close.icon
    .header
      | 选择参选奖项
    .content
      = form_tag [:admin, Rank.new], class: 'ui form', id: 'rankForm' do |f|
        .required.field
          = collection_check_boxes :rank, :award_ids, Award.where(innoaward_id: @innoaward.id), :id, :name do |c|
            .field.award-item
              .ui.checkbox
                = c.check_box
                = c.label
          = hidden_field_tag 'rank[product_id]'
          = hidden_field_tag :multi, true
    .actions
      .field
        = submit_tag '提交', class: 'ui blue button', id: 'rankSubmit'

app/views/admin/products/new.html.slim
.container
  = render partial: 'error_messages', locals: { errors: @product.errors }
  = render partial: 'form', locals: { innoaward: @innoaward, product: @product }

app/views/admin/products/show.html.slim
.container
  .ui.grid
    .column
      table.ui.celled.table
        thead
          tr
            th colspan='2'
              | 产品信息
        tbody
          tr
            td.four.wide
              | 产品LOGO
            td.twelve.wide
              = image_tag @product.logo.url || 'default_logo.jpg'
          tr
            td
              | 产品名称
            td
              = @product.name
          tr
            td
              | 产品网址
            td
              = @product.url
          tr
            td
              | 产品简介
            td
              = @product.summary
          tr
            td
              | 产品截图
            td
              - @product.screenshots.each do |ss|
                = image_tag ss.url ,class: 'product-pics'
          tr
            td
              | 上线时间
            td
              = @product.published_at
          tr
            td
              | 产品描述
            td
              = @product.description
          tr
            td
              | 产品类别
            td
              = @product.category
          tr
            td
              | 推荐平台
            td
              = @product.recommended_platform
          tr
            td
              | 微信ID
            td
              = @product.wechat
          tr
            td
              | 微博ID
            td
              = @product.weibo
          tr
            td
              | 联系人姓名
            td
              = @product.c_name
          tr
            td
              | 联系人公司/职位
            td
              = @product.c_corp + ' / ' + @product.c_position
          tr
            td
              | 联系人邮箱
            td
              = @product.c_email
          tr
            td
              | 联系人电话
            td
              = @product.c_mobile
          tr
            td
              | 编辑点评
            td
              = @product.evaluation
      .column
        a.ui.blue.button href=edit_admin_product_path(@product)
          | 编辑
        a.ui.red.button href=admin_products_path(@product) data-method='delete' data-confirm='确认删除？'
          | 删除